pid /tmp/nginx.pid;

events {}

http {
  upstream product_service {
    server product-service:4001;
  }

  upstream order_service {
    server order-service:4002;
  }

  upstream payment_service {
    server payment-service:4003;
  }

  upstream contact_service {
    server contact-service:4004;
  }

  server {
    listen 8080;

    location /api/products {
      proxy_pass http://product_service;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/orders {
      proxy_pass http://order_service;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/payments {
      proxy_pass http://payment_service;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/contact {
      proxy_pass http://contact_service;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}
