apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.frontend }}
  labels:
    app.kubernetes.io/part-of: shoppay
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.gateway }}
  labels:
    app.kubernetes.io/part-of: shoppay
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.product }}
  labels:
    app.kubernetes.io/part-of: shoppay
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.order }}
  labels:
    app.kubernetes.io/part-of: shoppay
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.payment }}
  labels:
    app.kubernetes.io/part-of: shoppay
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.contact }}
  labels:
    app.kubernetes.io/part-of: shoppay
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.vault }}
  labels:
    app.kubernetes.io/part-of: shoppay
