{{- if and .Values.networkPolicies .Values.networkPolicies.enabled }}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: order-default-deny
  namespace: {{ .Values.namespaces.order }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: order-allow-dns-egress
  namespace: {{ .Values.namespaces.order }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: order-service-allow-ingress-from-gateway
  namespace: {{ .Values.namespaces.order }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.orderService.name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.namespaces.gateway }}
      ports:
        - protocol: TCP
          port: {{ .Values.orderService.service.targetPort }}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: order-allow-egress-response
  namespace: {{ .Values.namespaces.order }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.orderService.name }}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.namespaces.gateway }}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: order-service-allow-egress-to-order-db
  namespace: {{ .Values.namespaces.order }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.orderService.name }}
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: order-postgresql
      ports:
        - protocol: TCP
          port: 5432

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: order-service-allow-egress-to-payment-service
  namespace: {{ .Values.namespaces.order }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.orderService.name }}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.namespaces.payment }}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ .Values.paymentService.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.paymentService.service.targetPort }}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: order-db-allow-ingress
  namespace: {{ .Values.namespaces.order }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: order-postgresql
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ .Values.orderService.name }}
      ports:
        - protocol: TCP
          port: 5432

{{- end }}
