apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.frontend.name }}
  namespace: {{ .Values.namespaces.frontend }}
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: shoppay
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.apiGateway.name }}
  namespace: {{ .Values.namespaces.gateway }}
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: shoppay
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.productService.name }}
  namespace: {{ .Values.namespaces.product }}
  labels:
    app.kubernetes.io/name: product-service
    app.kubernetes.io/part-of: shoppay
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.orderService.name }}
  namespace: {{ .Values.namespaces.order }}
  labels:
    app.kubernetes.io/name: order-service
    app.kubernetes.io/part-of: shoppay
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.paymentService.name }}
  namespace: {{ .Values.namespaces.payment }}
  labels:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/part-of: shoppay
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.contactService.name }}
  namespace: {{ .Values.namespaces.contact }}
  labels:
    app.kubernetes.io/name: contact-service
    app.kubernetes.io/part-of: shoppay
automountServiceAccountToken: false
