{{- if .Values.vault.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  labels:
    app.kubernetes.io/part-of: shoppay
    app.kubernetes.io/managed-by: Helm
spec:
  provider:
    vault:
      server: "http://vault.shoppay-vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets-role"
          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets"
{{- end }}
