apiVersion: v1
kind: Service
metadata:
  name: kong-admin-internal
  namespace: shoppay-gateway
  labels:
    app.kubernetes.io/name: kong-admin-internal
    app.kubernetes.io/part-of: shoppay
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: kong
    app.kubernetes.io/name: gateway
  ports:
    - name: admin-tls
      port: 8444
      targetPort: 8444
      protocol: TCP
