gateway:
  enabled: true
  replicaCount: 1

  env:
    database: "off"
    role: traditional
    router_flavor: traditional
    nginx_worker_processes: "1"

    proxy_access_log: /dev/stdout
    proxy_error_log: /dev/stderr

    admin_access_log: /dev/stdout
    admin_error_log: /dev/stderr

    status_listen: "0.0.0.0:8100"
    admin_listen: "0.0.0.0:8444 ssl"

  proxy:
    enabled: true
    type: NodePort
    http:
      enabled: true
      servicePort: 80
      containerPort: 8000
      nodePort: 30080
    tls:
      enabled: false

  admin:
    enabled: true
    type: ClusterIP
    http:
      enabled: false
    tls:
      enabled: true
      servicePort: 8444
      containerPort: 8444

  manager:
    enabled: false

  portal:
    enabled: false

  portalapi:
    enabled: false

  postgresql:
    enabled: false

  readinessProbe:
    httpGet:
      path: /status
      port: status
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 12

  livenessProbe:
    httpGet:
      path: /status
      port: status
    initialDelaySeconds: 40
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 6

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

controller:
  enabled: true

  ingressController:
    enabled: true
    installCRDs: false
    ingressClass: kong

    gatewayDiscovery:
      enabled: false

    env:
      kong_admin_url: "https://kong-admin-internal.shoppay-gateway.svc.cluster.local:8444"
      kong_admin_tls_skip_verify: "true"
      publish_service: shoppay-gateway/kong-gateway-proxy

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
