stages:
  - validate
  - build
  - security

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  DOCKER_BUILDKIT: "1"

default:
  interruptible: true

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
    - if: $CI_COMMIT_BRANCH == "main"

cache:
  paths:
    - frontend/node_modules/
    - backend/services/product-service/node_modules/
    - backend/services/order-service/node_modules/
    - backend/services/payment-service/node_modules/
    - backend/services/contact-service/node_modules/

# =========================
# VALIDATION STAGE
# =========================

frontend_lint:
  stage: validate
  image: node:22-alpine
  script:
    - cd frontend
    - npm ci
    - npm run lint

frontend_build:
  stage: validate
  image: node:22-alpine
  before_script:
    - cd frontend
    - npm ci
  script:
    - npm run build

backend_product_build:
  stage: validate
  image: node:22-alpine
  before_script:
    - cd backend/services/product-service
    - npm ci --omit=dev
  script:
    - node --check src/index.js

backend_order_build:
  stage: validate
  image: node:22-alpine
  before_script:
    - cd backend/services/order-service
    - npm ci --omit=dev
  script:
    - node --check src/index.js

backend_payment_build:
  stage: validate
  image: node:22-alpine
  before_script:
    - cd backend/services/payment-service
    - npm ci --omit=dev
  script:
    - node --check src/index.js

backend_contact_build:
  stage: validate
  image: node:22-alpine
  before_script:
    - cd backend/services/contact-service
    - npm ci --omit=dev
  script:
    - node --check src/index.js

helm_validate:
  stage: validate
  image: alpine:3.20

  before_script:
    - apk add --no-cache curl bash git openssl
    - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

  script:
    - helm version
    - helm lint charts/shoppay
    - helm template shoppay charts/shoppay > shoppay-rendered.yaml

  artifacts:
    paths:
      - shoppay-rendered.yaml

dockerfile_lint:
  stage: validate
  image: hadolint/hadolint:latest-debian

  script:
    - hadolint backend/services/product-service/Dockerfile
    - hadolint backend/services/order-service/Dockerfile
    - hadolint backend/services/payment-service/Dockerfile
    - hadolint backend/services/contact-service/Dockerfile
    - hadolint frontend/Dockerfile

# =========================
# BUILD & PUSH STAGE
# =========================

.build_template:
  stage: build
  image: docker:27.0.3

  services:
    - docker:27.0.3-dind

  before_script:
    - docker info
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

docker_build_product:
  extends: .build_template
  script:
    - docker build -t $DOCKERHUB_USERNAME/shoppay-product:$IMAGE_TAG ./backend/services/product-service
    - docker push $DOCKERHUB_USERNAME/shoppay-product:$IMAGE_TAG

docker_build_order:
  extends: .build_template
  script:
    - docker build -t $DOCKERHUB_USERNAME/shoppay-order:$IMAGE_TAG ./backend/services/order-service
    - docker push $DOCKERHUB_USERNAME/shoppay-order:$IMAGE_TAG

docker_build_payment:
  extends: .build_template
  script:
    - docker build -t $DOCKERHUB_USERNAME/shoppay-payment:$IMAGE_TAG ./backend/services/payment-service
    - docker push $DOCKERHUB_USERNAME/shoppay-payment:$IMAGE_TAG

docker_build_contact:
  extends: .build_template
  script:
    - docker build -t $DOCKERHUB_USERNAME/shoppay-contact:$IMAGE_TAG ./backend/services/contact-service
    - docker push $DOCKERHUB_USERNAME/shoppay-contact:$IMAGE_TAG

docker_build_frontend:
  extends: .build_template
  script:
    - |
      docker build \
      --build-arg NEXT_PUBLIC_API_BASE_URL=/api \
      -t $DOCKERHUB_USERNAME/shoppay-frontend:$IMAGE_TAG \
      ./frontend

    - docker push $DOCKERHUB_USERNAME/shoppay-frontend:$IMAGE_TAG

# =========================
# SECURITY STAGE
# =========================

.trivy_template:
  stage: security
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]

trivy_product_fs:
  extends: .trivy_template

  script:
    - |
      trivy fs \
      --severity HIGH,CRITICAL \
      --exit-code 1 \
      --format json \
      --output trivy-product-report.json \
      ./backend/services/product-service

  artifacts:
    when: always
    paths:
      - trivy-product-report.json

trivy_product_image:
  extends: .trivy_template

  script:
    - |
      trivy image \
      --severity HIGH,CRITICAL \
      --exit-code 1 \
      $DOCKERHUB_USERNAME/shoppay-product:$IMAGE_TAG

trivy_order_image:
  extends: .trivy_template

  script:
    - |
      trivy image \
      --severity HIGH,CRITICAL \
      --exit-code 1 \
      $DOCKERHUB_USERNAME/shoppay-order:$IMAGE_TAG

trivy_payment_image:
  extends: .trivy_template

  script:
    - |
      trivy image \
      --severity HIGH,CRITICAL \
      --exit-code 1 \
      $DOCKERHUB_USERNAME/shoppay-payment:$IMAGE_TAG

trivy_contact_image:
  extends: .trivy_template

  script:
    - |
      trivy image \
      --severity HIGH,CRITICAL \
      --exit-code 1 \
      $DOCKERHUB_USERNAME/shoppay-contact:$IMAGE_TAG

trivy_frontend_image:
  extends: .trivy_template

  script:
    - |
      trivy image \
      --severity HIGH,CRITICAL \
      --exit-code 1 \
      $DOCKERHUB_USERNAME/shoppay-frontend:$IMAGE_TAG

trivy_secrets:
  extends: .trivy_template

  script:
    - trivy fs --scanners secret --exit-code 1 .


trivy_k8s_config:
  stage: security
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]

  script:
    - trivy config \
      --severity HIGH,CRITICAL \
      --exit-code 1 \
      --ignorefile .trivyignore \
      charts/shoppay
