apiVersion: v1
kind: Pod
metadata:
  name: curl-test
  namespace: shoppay-gateway
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: curl
    image: curlimages/curl:8.8.0
    command:
    - sleep
    - "3600"
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop:
        - ALL
  restartPolicy: Never
