{{- if .Values.monitoring.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product-service-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}-monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: product-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order-service-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}-monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: order-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: payment-service-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}-monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: payment-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: contact-service-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}-monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: contact-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
