global:
  projectName: shoppay
  environment: dev

namespaces:
  frontend: shoppay-frontend
  gateway: shoppay-gateway
  product: shoppay-product
  order: shoppay-order
  payment: shoppay-payment
  contact: shoppay-contact
  vault: shoppay-vault

serviceAccounts:
  frontend:
    name: frontend-sa
  apiGateway:
    name: api-gateway-sa
  productService:
    name: product-service-sa
  orderService:
    name: order-service-sa
  paymentService:
    name: payment-service-sa
  contactService:
    name: contact-service-sa

productPostgresql:
  enabled: true

orderPostgresql:
  enabled: true

paymentPostgresql:
  enabled: true

contactPostgresql:
  enabled: true

product-postgresql:
  enabled: true
  namespaceOverride: shoppay-product
  architecture: standalone
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 17.6.0-debian-12-r4
  auth:
    username: product_user
    database: productdb
    existingSecret: product-db-credentials
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password
  primary:
    persistence:
      enabled: true
      storageClass: local-path
      size: 2Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    podSecurityContext:
      enabled: true
      fsGroup: 1001
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsGroup: 1001
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault

order-postgresql:
  enabled: true
  namespaceOverride: shoppay-order
  architecture: standalone
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 17.6.0-debian-12-r4
  auth:
    username: order_user
    database: orderdb
    existingSecret: order-db-credentials
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password
  primary:
    persistence:
      enabled: true
      storageClass: local-path
      size: 2Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    podSecurityContext:
      enabled: true
      fsGroup: 1001
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsGroup: 1001
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault

payment-postgresql:
  enabled: true
  namespaceOverride: shoppay-payment
  architecture: standalone
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 17.6.0-debian-12-r4
  auth:
    username: payment_user
    database: paymentdb
    existingSecret: payment-db-credentials
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password
  primary:
    persistence:
      enabled: true
      storageClass: local-path
      size: 2Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    podSecurityContext:
      enabled: true
      fsGroup: 1001
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsGroup: 1001
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault

contact-postgresql:
  enabled: true
  namespaceOverride: shoppay-contact
  architecture: standalone
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 17.6.0-debian-12-r4
  auth:
    username: contact_user
    database: contactdb
    existingSecret: contact-db-credentials
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password
  primary:
    persistence:
      enabled: true
      storageClass: local-path
      size: 2Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    podSecurityContext:
      enabled: true
      fsGroup: 1001
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsGroup: 1001
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault

productService:
  enabled: true
  name: product-service
  namespace: shoppay-product
  replicaCount: 1

  image:
    repository: selconyt/shoppay-product-service
    tag: v11
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 4001
    targetPort: 4001

  env:
    port: "4001"
    databaseHost: shoppay-product-postgresql
    databasePort: "5432"
    databaseName: productdb
    databaseUser: product_user
    databaseSecretName: product-db-credentials
    databasePasswordKey: password

  vault:
    enabled: true
    role: product-service
    secretPath: secret/data/shoppay/product-service/admin-auth
    authFile: /vault/secrets/admin-auth.json

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi



contactService:
  enabled: true
  name: contact-service
  namespace: shoppay-contact
  replicaCount: 1

  image:
    repository: selconyt/shoppay-contact-service
    tag: v7
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 4004
    targetPort: 4004

  env:
    port: "4004"
    databaseHost: shoppay-contact-postgresql
    databasePort: "5432"
    databaseName: contactdb
    databaseUser: contact_user
    databaseSecretName: contact-db-credentials
    databasePasswordKey: password

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

paymentService:
  enabled: true
  name: payment-service
  namespace: shoppay-payment
  replicaCount: 1

  image:
    repository: selconyt/shoppay-payment-service
    tag: v7
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 4003
    targetPort: 4003

  env:
    port: "4003"
    databaseHost: shoppay-payment-postgresql
    databasePort: "5432"
    databaseName: paymentdb
    databaseUser: payment_user
    databaseSecretName: payment-db-credentials
    databasePasswordKey: password

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

orderService:
  enabled: true
  name: order-service
  namespace: shoppay-order
  replicaCount: 1

  image:
    repository: selconyt/shoppay-order-service
    tag: v7
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 4002
    targetPort: 4002

  env:
    port: "4002"
    databaseHost: shoppay-order-postgresql
    databasePort: "5432"
    databaseName: orderdb
    databaseUser: order_user
    databaseSecretName: order-db-credentials
    databasePasswordKey: password
    paymentServiceUrl: "http://payment-service.shoppay-payment.svc.cluster.local:4003"

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: true
  className: kong

frontend:
  enabled: true
  name: frontend
  namespace: shoppay-frontend
  replicaCount: 2

  image:
    repository: selconyt/shoppay-frontend
    tag: v17
    pullPolicy: IfNotPresent

  service:
    type: NodePort
    port: 3000
    targetPort: 3000
    nodePort: 30000

  env:
    port: "3000"

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

networkPolicies:
  enabled: true
grafana:
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/grafana/"
      serve_from_sub_path: true
