# infra/vault/vault-secretstore.yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault.shoppay-vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets-role"
          serviceAccountRef:
            name: "external-secrets" # تأكد أن هذا هو اسم الـ SA الخاص بـ ESO
            namespace: "external-secrets" # تأكد أن هذا هو الـ Namespace المثبت فيه ESO
