apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: interprise-onpremshoppay
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/MohamedMahmoudDesouky/Interprise-OnPremShopPay.git
    targetRevision: HEAD
    path: charts/shoppay
    helm:
      releaseName: shoppay

  destination:
    server: https://kubernetes.default.svc
    namespace: shoppay

  ignoreDifferences:
    # HPA يتحكم في عدد الـ replicas — نتجاهل الفرق لتجنب OutOfSync
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # مطلوب للـ CRDs الكبيرة مثل Prometheus

